spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/koi_user?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: abc123
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

  redis:
    host: 192.168.58.100
    port: 6379
    database: 0
    timeout: 1800000
    password: 123
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  mode: qiniu
  qiniu:
    url: https://cdn.koicode.cn/
    access-key: C9sX0jBml_9LT245OrS6Bxlb6uhp1DQeoshjGuuJ
    secret-key: XA6U40SJrVI2nAqT_Ff9plPxFWWeMKdgxYFTWzjG
    bucket: jinri-container
    domain: cdn.koicode.cn