server:
  port: 48080
spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务

  application:
    name: gateway-server

  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: ${koiuser.nacos.addr}

    gateway:
      routes:
        ## system-server 服务
        - id: system-admin-api
          uri: lb://system-server
          predicates:
            - Path=/admin-api/system/**
          filters:
            - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs
        - id: system-app-api
          uri: lb://system-server
          predicates:
            - Path=/app-api/system/**
          filters:
            - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs

        ## interfacer-server 服务
        - id: interface-admin-api
          uri: lb://interfacer-server
          predicates:
            - Path=/admin-api/interface/**
          filters:
            - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs
        - id: interface-app-api
          uri: lb://interfacer-server
          predicates:
            - Path=/app-api/interface/**
          filters:
            - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs


  redis:
    host: ${koiuser.redis.host}
    port: ${koiuser.redis.port}
    database: 0
    timeout: 1800000
    password: ${koiuser.redis.password}
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20