spring:
  redis:
    host: 192.168.245.100
    port: 6379
    database: 0
    timeout: 1800000
    password: abc123
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
