server:
  port: 8302
spring:
  application:
    name: koiUser
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${koiUser.mysql.ip}:${koiUser.mysql.port}/${koiUser.mysql.db}?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ${koiUser.mysql.username}
    password: ${koiUser.mysql.password}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: ${koiUser.redis.host}
    port: ${koiUser.redis.port}
    database: 0
    timeout: 1800000
    password: ${koiUser.redis.password}
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20
  jackson:
    serialization:
      write-dates-as-timestamps: true


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.koi.koiuserserver.controller